-- MySQL Script generated by MySQL Workbench
-- Thu Apr 18 18:58:44 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema ab1_tp8_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ab1_tp8_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS ab1_tp8_db DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE ab1_tp8_db ;

-- -----------------------------------------------------
-- Table `ab1_tp8_db`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ab1_tp8_db`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `dni` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `contactoAlternativo` BIGINT(20) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `telefono` BIGINT(20) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ab1_tp8_db`.`mascotas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ab1_tp8_db`.`mascotas` (
  `idmascotas` INT NOT NULL AUTO_INCREMENT,
  `cliente_idcliente` INT NOT NULL,
  `alias` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `especie` VARCHAR(45) NOT NULL,
  `mascotascol` VARCHAR(45) NOT NULL,
  `calorPelo` VARCHAR(45) NOT NULL,
  `fechaNac` DATE NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idmascotas`),
  INDEX `fk_mascotas_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  CONSTRAINT `fk_mascotas_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `ab1_tp8_db`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ab1_tp8_db`.`tratamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ab1_tp8_db`.`tratamiento` (
  `idTratamiento` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `medicamento` VARCHAR(45) NOT NULL,
  `importe` DOUBLE NOT NULL,
  `tipoTratamiento` VARCHAR(45) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  PRIMARY KEY (`idTratamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ab1_tp8_db`.`visita`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ab1_tp8_db`.`visita` (
  `idvisita` INT NOT NULL AUTO_INCREMENT,
  `mascotas_idmascotas` INT NOT NULL,
  `tratamiento_idTratamiento` INT NOT NULL,
  `fechaVisita` DATE NULL,
  `detalle` VARCHAR(45) NULL,
  `peso` DOUBLE NULL,
  `activo` TINYINT(1) NULL,
  PRIMARY KEY (`idvisita`),
  INDEX `fk_visita_mascotas1_idx` (`mascotas_idmascotas` ASC) VISIBLE,
  INDEX `fk_visita_tratamiento1_idx` (`tratamiento_idTratamiento` ASC) VISIBLE,
  CONSTRAINT `fk_visita_mascotas1`
    FOREIGN KEY (`mascotas_idmascotas`)
    REFERENCES `ab1_tp8_db`.`mascotas` (`idmascotas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visita_tratamiento1`
    FOREIGN KEY (`tratamiento_idTratamiento`)
    REFERENCES `ab1_tp8_db`.`tratamiento` (`idTratamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



